---
title: "Atividades"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Abaixo seguem as atividades de cada módulo do curso a serem efetuadas pelos alunos, bem como o link de envio do trabalho e a respectiva data limite de envio:

## Curso Básico

- **Introdução ao R – Felipe (envio até 29/08/2018)**

Exercício 1: [baixar](roteiro_atividade-1_2018-2.docx) - Dados: [arvores](arvores.xlsx), [bancodedados1](bancodedados11.xlsx) - Link de envio da atividade: [acessar](https://docs.google.com/forms/d/e/1FAIpQLSdqWi3KvJoe9n5eb-FaM4JFNfylRB_3O6zpP--7HB-K2X7LSw/viewform)


- **Estatística Descritiva – Denize (envio até 03/09/2018)**

Exercício 2: [baixar1](os2_lab_01A_port.pdf) [baixar2](Atividades_para_entregar.docx) - Link de envio da atividade: [acessar](https://docs.google.com/forms/d/e/1FAIpQLSfhXlR_3008yldRnCjmKmszUO9dghc81AoaSUB1_lt19QPNpg/viewform)


- **Inferência Estatística – Tatiane (envio até 05/09/2018)**

Exercício 3: [baixar]() - Link de envio da atividade: [acessar](https://docs.google.com/forms/d/e/1FAIpQLScJAAT_e4lBCuOnEuktDoNPFEu_GNrfHcJM8VYEaS5-IIzMVw/viewform)

- **Teste de qui-quadrado – Denize/Tati (envio até 06/09/2018)**

Exercício 4: [baixar]() - Link de envio da atividade: [acessar](https://docs.google.com/forms/d/e/1FAIpQLSf3_b5cNzAcVwib5PF-xgLUcAOqcvYRD7ACV7HUV-vauOnDdw/viewform)

- **Modelos de regressão - Iara (envio até 12/09/2018)**

Exercício 5: [baixar1](Exercícios_encontro_5_módulo_básico.docx), [baixar2](peixes1.xls) - Link de envio da atividade: [acessar](https://docs.google.com/forms/d/e/1FAIpQLSc4V5tQ8QH9Y0k1yrdPwMAGe7K-M6PKgEISxf5iMoXtPhUPFQ/viewform)
 
## Curso Avançado


- **<!--12/09/2018-->Experimentação - Tatiane (envio até 19/09/2018)**

Exercício 6: [baixar]() - Link de envio da atividade: [acessar](https://docs.google.com/forms/d/e/1FAIpQLSeWRRXj3BCdRXi7wtcVAARwBhLIzihcl0JrGXPhHa2pWKSjJw/viewform)

- **<!--13/09/2018-->Análise fatorial – Denize (envio até 20/09/2018)**

Exercício 7: [baixar](Análise_Fatorial.docx) - Dados: [baixar](Creme_dental_curso.xlsx) - Link de envio da atividade: [acessar](https://docs.google.com/forms/d/e/1FAIpQLSdWP2NrvN4YmJpumkk2j14F-j4yEmiA6MYs1cKUR0ELctqRCQ/viewform)

- **<!--19/09/2018-->Modelos de regressão múltipla – Iara (envio até 26/09/2018)**

Exercício 8: [baixar]() - Link de envio da atividade: [acessar](https://docs.google.com/forms/d/e/1FAIpQLScU_i6EX4MsXSDWY-wVqAKBKZR9MiGMGIVx9-6C3es2PKxWIQ/viewform)

- **<!--26/09/2018--> – Modelos de regressão logística – Felipe (envio até 03/10/2018)**

Exercício 9: [baixar]() - Link de envio da atividade: [acessar](https://docs.google.com/forms/d/e/1FAIpQLSd6zTvEVpjlyD498ePIE8_swcSiUFSIYCBUdRwRaeDQO3pElw/viewform)

- **<!--27/09/2018-->RMarkdown - Letícia (envio até 04/10/2018)**

Exercício 10: [baixar]() - Link de envio da atividade: [acessar](https://docs.google.com/forms/d/e/1FAIpQLSeQ31zqISBiojF2-QoPMyqa-Ek9_qNQ9I5u7ELCP4Lt2IRbEw/viewform)


